[project]
name = "motor-learning-network"
description = "A short description of the project."
version = "0.1.0"
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
python = "~=3.10.0"
loguru = "*"
pytest = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"
pandas = ">=2.3.3,<3"
bokeh = ">=3.8.2,<4"
ipython = ">=8.37.0,<9"
ipykernel = ">=7.1.0,<8"
biopython = ">=1.86,<2"
transformers = "==4.44.2"
bert-extractive-summarizer = "==0.10.1"
huggingface_hub = "==0.36.0"
tokenizers = "==0.19.1"
nbformat = ">=5.10.4,<6"
pygls = "<2.0.0"
habanero = ">=2.3.0,<3"
pyarrow = ">=23.0.0,<24"

[pypi-dependencies]
mkdocs = "*"
python-dotenv = "*"
motor_learning_network = { path = ".", editable = true }
pybibx = ">=5.2.8, <6"
pymedx = ">=0.5.1, <0.6"
sf-hamilton = { version = ">=1.89.0, <2", extras = ["lsp"] }
pygls = "==1.3.1"
pyarrow = "*"

[feature.simple.dependencies]
python = "3.12.12.*"
ipython = ">=9.10.0,<10"
ipykernel = ">=7.1.0,<8"
nbformat = ">=5.10.4,<6"
habanero = ">=2.3.0,<3"

[feature.simple.pypi-dependencies]
annotated-types = "==0.7.0"
anyio = "==4.12.1"
bert-extractive-summarizer = "==0.10.1"
bertopic = "==0.17.4"
blis = "==1.3.3"
catalogue = "==2.0.10"
certifi = "==2026.1.4"
chardet = "==5.2.0"
charset-normalizer = "==3.4.4"
click = "==8.3.1"
cloudpathlib = "==0.23.0"
cohere = "==5.20.2"
confection = "==0.1.5"
contourpy = "==1.3.3"
cycler = "==0.12.1"
cymem = "==2.0.13"
diskcache = "==5.6.3"
distro = "==1.9.0"
fastavro = "==1.12.1"
filelock = "==3.20.3"
fonttools = "==4.61.1"
fsspec = "==2025.3.0"
gensim = "==4.4.0"
google-ai-generativelanguage = "==0.6.15"
google-api-core = "==2.29.0"
google-api-python-client = "==2.188.0"
google-auth-httplib2 = "==0.3.0"
google-auth = "==2.47.0"
google-generativeai = "==0.8.6"
googleapis-common-protos = "==1.72.0"
h11 = "==0.16.0"
hdbscan = "==0.8.41"
hf-xet = "==1.2.0"
httpcore = "==1.0.9"
httplib2 = "==0.31.2"
httpx = "==0.28.1"
huggingface-hub = "==0.36.0"
idna = "==3.11"
jinja2 = "==3.1.6"
jiter = "==0.12.0"
joblib = "==1.5.3"
keybert = "==0.9.0"
kiwisolver = "==1.4.9"
llmx = "==0.0.21a0"
llvmlite = "==0.43.0"
markdown-it-py = "==4.0.0"
markupsafe = "==3.0.3"
matplotlib = "==3.10.0"
mdurl = "==0.1.2"
mpmath = "==1.3.0"
murmurhash = "==1.0.15"
networkx = "==3.6.1"
numba = "==0.60.0"
numpy = "==2.0.2"
openai = "==2.16.0"
pandas = { version = ">=3.0.0, <4", extras = ["pyarrow"] }
pillow = "==11.3.0"
plotly = "==5.24.1"
preshed = "==3.0.12"
proto-plus = "==1.27.0"
protobuf = "==5.29.5"
pyasn1-modules = "==0.4.2"
pyasn1 = "==0.6.2"
pybibx = "==5.2.8"
pydantic-core = "==2.41.4"
pydantic = "==2.12.3"
pygments = "==2.19.2"
pynndescent = "==0.6.0"
pyparsing = "==3.3.2"
python-dateutil = "==2.9.0.post0"
pytz = "==2025.2"
pyyaml = "==6.0.3"
regex = "==2025.11.3"
requests = "==2.32.4"
rich = "==13.9.4"
rsa = "==4.9.1"
safetensors = "==0.7.0"
scikit-learn = "==1.6.1"
scipy = "==1.16.3"
sentence-transformers = "==5.2.2"
sentencepiece = "==0.2.1"
setuptools = "==75.2.0"
shellingham = "==1.5.4"
six = "==1.17.0"
smart-open = "==7.5.0"
sniffio = "==1.3.1"
spacy-legacy = "==3.0.12"
spacy-loggers = "==1.0.5"
spacy = "==3.8.11"
srsly = "==2.5.2"
sympy = "==1.14.0"
tenacity = "==9.1.2"
thinc = "==8.3.10"
threadpoolctl = "==3.6.0"
tiktoken = "==0.12.0"
tokenizers = "==0.22.2"
tqdm = "==4.67.*"
transformers = "==4.57.6"
typer-slim = "==0.21.1"
typer = "==0.21.1"
types-requests = "==2.32.4.20260107"
typing-extensions = "==4.15.0"
typing-inspection = "==0.4.2"
tzdata = "==2025.3"
umap-learn = "==0.5.11"
uritemplate = "==4.2.0"
wasabi = "==1.1.3"
weasel = "==0.4.3"
wordcloud = "==1.9.6"
pip = ">=26.0, <27"
dill = ">=0.4.1, <0.5"
nbformat = ">=5.10.4, <6"
dotenv = ">=0.9.9, <0.10"
sf-hamilton = { version = ">=1.89.0, <2", extras = ["lsp"] }
pygls = "==1.3.1"
pyarrow = ">=23.0.0, <24"

[environments]
simple = { features = ["simple"], no-default-feature = true }
