[project]
name = "motor-learning-network"
description = "A short description of the project."
version = "0.1.0"
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
python = "~=3.10.0"
loguru = "*"
pytest = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"
pandas = ">=2.3.3,<3"
bokeh = ">=3.8.2,<4"
ipython = ">=8.37.0,<9"

[pypi-dependencies]
mkdocs = "*"
python-dotenv = "*"
motor_learning_network = { path = ".", editable = true }
sf-hamilton = {version=">=1.89.0, <2", extras = ["visualization"]}
